# Generated by Django 4.0.1 on 2022-01-31 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20220130_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='search_count',
            field=models.IntegerField(default=0),
        ),
    ]
